config/routes.rb
Dojo4::Application.routes.draw do
#
  extend Upload::Routes

#
  match "api(/*path(.:format))" => "api#index", :as => "api"

#
  scope(nil) do
    AuthController::Routes.each do |route|
      match "#{ route }(/:token)"   => "auth##{ route }", :as => "#{ route }"
    end
  end
  scope('auth') do
    AuthController::Routes.each do |route|
      match "#{ route }(/:token)"   => "auth##{ route }", :as => "auth_#{ route }"
    end
  end
  scope('admin') do
    AuthController::Routes.each do |route|
      match "#{ route }(/:token)"   => "admin/auth##{ route }", :as => "admin_#{ route }"
    end
  end
  scope('admin/auth') do
    AuthController::Routes.each do |route|
      match "#{ route }(/:token)"   => "admin/auth##{ route }", :as => "admin_auth_#{ route }"
    end
  end


#
  resources :invitations do
    member do
      match :accept
      match :decline
    end
  end


#
  match 'dashboard(/:action(/:id(.:format)))', :controller => 'dashboard', :as => 'dashboard'

## /su/jobs interface
#
=begin
  require 'resque'
  require 'resque/server'
  mount(Resque::Server => '/resque/jobs', :constraints => Constraints.admin)
=end


## admin
#
  namespace :admin do
    resources :users do
      match 'welcome', :action => 'welcome', :as => :welcome
    end

    location_routes = proc do
      resources :locations, :controller => 'locations'  do
        collection do
          match 'job/:id', :action => 'job'
          match 'import', :action => 'import'
        end
      end
    end
    instance_eval(&location_routes)

    resources :brands do
      instance_eval(&location_routes)
    end

    resources :reports do
      match 'attachments/:attachment_id', :action => 'attachment', :as => 'attachment', :via => 'get'
    end

    resources :uploads
  end

  match 'admin(/:action(/:id(.:format)))', :controller => 'admin/application', :as => 'admin'

## su
#
  namespace :su do
    resources :uploads
    resources :jobs
    match 'test(/:action(/:id(.:format)))', :controller => 'test'
  end
  match 'su(/:action(/:id(.:format)))', :controller => 'su/application', :as => 'su'


  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
    root :to => 'root#index', :as => :root

    match 'csrf' => 'application#csrf'
    match 'flash_messages' => 'application#flash_messages'

##
#
  scope ':brand' do
    match ':controller(/:action)(.:format)', :constraints => Constraints.brand
  end
  resources :brands do
    #match ':id/locator', :action => 'locator'
    member do
      match :locator
      match :contact
    end
  end

  resources :locations do
    collection do
      match :locator
    end
  end

  match 'javascript_jobs(/:action(/:id))(.:format)', :controller => 'javascript_jobs'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/shared/_flash.html.erb
<div class='flash' style='display:none'>
</div>

<noscript>
  <div class="flash">
    <div class="error">
      <span class="message">You need javascript enabled for the internet to function properly.</span>
    </div>
  </div>
</noscript>

app/views/shared/_google_analytics.html.erb
<!--
  google analytics
-->

<% unless local_request? %>

  <script type="text/javascript">

/*
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-19876807-2']);
    _gaq.push(['_setDomainName', window.location.host.split('.').splice(-2,2).join('.')]);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
*/

  </script>

<% end %>

app/views/shared/_google_maps.html.erb
<script type="text/javascript">
  function initialize_maps() {
    window.App && window.App.initialize_maps();
  };

  function loadGoogleMaps() {
    var type = "text/javascript";
    var src = '//maps.googleapis.com/maps/api/js?sensor=false&callback=initialize_maps';
    var script = document.createElement("script");
    script.type = type;
    script.src = src;
    //alert(' document.location.protocol: ' +  document.location.protocol);
    document.body.appendChild(script);
  };

  jq(function(){
    loadGoogleMaps();
  });
</script>

app/views/shared/_header.html.erb
<br>

<div class='row-fluid' style='vertical-align:middle;'>

  <div class='span6'>
    <%=
      link_to(image_tag('logo.png', :id => :logo), '/')
    %>
  </div>

  <div class='span6' style='text-align:right;'>
    <% unless @layout.nav_for(:auth).blank? %>

      <nav role="navigation">
        <% @layout.nav_for(:auth).map do |link| %>
          <%= link_to link.content, link.url, link.options %><%= ' | ' unless link == link.nav.last %>
        <% end %>
      </nav>

    <% end %>
  </div>
</div>

<br>

app/views/shared/_nav.html.erb
<%=

  unless @layout.nav_for(:main).blank?

    nav_{
      ul_(:class => 'nav nav-tabs'){
        @layout.nav_for(:main).each do |link|

         active_class = (link.active ? 'active' : 'inactive')

          case link.config[:type].to_s
          #
            when /dropdown/
              li_(:class => "#{ active_class } dropdown"){
                a_(:class => 'dropdown-toggle', :data_toggle => 'dropdown', :href => (link.href || '#')){
                  tagz << link.content
                  tagz << ' '
                  b_(:class => 'caret'){ ' ' }
                }

                ul_(:class => 'dropdown-menu'){
                  link.config.menu.each do |item|
                    case
                      when item == :_divider
                        li_(:class => 'divider'){}

                      when item.is_a?(Array)
                        content, href, *ignored = item
                        li_{ a_(:href => href){ content } }

                      when item.is_a?(Hash)
                        item = Map.for(item)
                        li_{ a_(:href => item[:href]){ item[:content] } }

                      else
                        li_{ a_(:href => item.to_s){ item.to_s } }
                    end
                  end
                }
              }
          #
            else
              li_(:class => "#{ active_class }"){
                a_(:href => link.href){ link }
              }
          end

        end
      }
    }

  end

%>

app/views/shared/_s3_upload.html.erb
<script>
  $(function(){
  //
    s3Uploader.ify({
      'ajax' : true
    });

  //
    var progress = {};

  //
    s3Uploader.callbacks['before'] = function(data){
      var s3uploader   = data.s3uploader;
      var url          = data.url;
      var filename     = data.filename;
      var content_type = data.content_type;

      var html = "";

      html += "<div class='upload' style='opacity: 0.5;'>";
      html +=   "<div class='filename' style='white-space: nowrap; overflow: hidden; text-overflow: ellipsis; border-top: 1px solid #ccc; margin-top: 1em; padding-top: 0.5em;'></div>";

      html +=   "<img style='display:none; margin-top: 1em; max-width: 100%;' >";

      html +=   "<div class='progress active progress-warning progress-striped' style='display:block; margin-top: 1em;'>"
      html +=     "<div class='bar' style='width: 0%'>";
      html +=   "</div></div>";
      html += "</div>";

      $html = $(html);

      var $filename = $html.find('.filename');
      var width = s3uploader.input.width();

      $filename.html(filename);

      s3uploader.input.after($html);

      progress[url] = $html;
    };

  //
    s3Uploader.callbacks['progress'] = function(data){
      var s3uploader = data.s3uploader; 
      var url          = data.url;

      var percent = data.percent;

      var $html = progress[url];

      var width = percent + '%';
      var $bar = $html.find('.bar');
      $bar.css({'width' : width});
    };

  //
    s3Uploader.callbacks['success'] = function(data){
      var s3uploader = data.s3uploader;
      var url          = data.url;
      var content_type = data.content_type;
      var filename = data.filename;

      var $html = progress[url];

      $html.css({'opacity' : '1.0'});
      $html.find('.progress').hide();

      var $filename = $html.find('.filename');

      var link = $('<a>');
      link.html(filename);
      link.attr('href', url);
      link.attr('target', '_blank');
      $filename.html(link);

      var width = s3uploader.input.width();

      if( content_type.match(/image\//) && content_type.match(/png|jpg|jpeg|gif/) ){
        var $img = $html.find('img');
        $img.show();
        $img.css({'diplay' : 'block'});
        $img.css({'max-width' : width});
        $img.attr('src', url);
      };
    };

  });
</script>

app/views/shared/_scripts.html.erb
<!-- flash -->

  <script>
    jQuery(function(){
      var list = <%= j messages! %>;

      jQuery.each(list, function(index, pair){
        var message = pair[0];
        var options = pair[1];

        App.flash(message, options);
      });
    });
  </script>

<!-- csrf -->

  <script>
    jQuery(function() {
      jQuery.getJSON('/csrf.json', function(csrf) {
        jQuery("meta[name='csrf-token']").attr('content', csrf.token);
        jQuery("meta[name='csrf-param']").attr('content', csrf.param);
      });
    });
  </script>

app/views/shared/_server_info.html.erb
<script>
  App.server_info = <%=
    j App.server_info
  %>;
</script>

app/views/shared/_templates.html.erb
<!-- templates -->

  <!-- flash -->
  <%= template_for 'flash-list-item' do %>
    <div class='alert message'>
      <a class='dismiss close' href='javascript:void(42)'>&#215;</a>
      {{{ message }}}
    </div>
  <% end %>

app/views/shared/_upload.html.erb
<%
  domid = "file-uploader-#{ App.uuid }"

  if defined?(config)
    config = Map.for(config)
  else
    config = Map.new
  end
%>

<script>
  if(!window.Upload){
    Upload = {};

    Upload.callbacks = {};

    Upload.callbacks.complete = function(response){
      return true;
    };

    Upload.callbacks.embed = function(content){
      return true;
    };

    Upload.callbacks.remove = function(content){
      return true;
    };

    Upload.callbacks.unremove = function(content){
      return true;
    };
  };
</script>

<!--
  stylez
-->

  <% content_for :style do %>
    <style>
      .qq-upload-button {
        background-color: #999;
        border-radius: 5px;
        -moz-border-radius: 5px;
      }
      .qq-upload-list li.qq-upload-success {
        background-color: #ccc;
        display: none;
      }
      .qq-upload-file ,
      .qq-upload-size
      {
        display: none;
      }
      .qq-upload-button {
        width: 100%;
      }
    </style>
  <% end %>

<!--
  where uploaded files appear
-->

  <table id='uploads' class='table table-striped' style='width:100%;margin:0em 0em;'>
    <script name='upload-row' class='template' type='text/template'>

      <tr>
        <td style='vertical-align:top;'>
          {{#if is_image}}

            <a href="javascript:void(42)" class="upload-preview" data-preview="{{ url }}">
              <img src="{{ url }}" alt="{{ filename }}" style="max-width:100px;max-height:100px;padding-right:1em;" />
            </a>

          {{/if}}

          {{#unless is_image}}

            <nobr style="display:block;padding:1em;min-width:8em;height:3em;background-color:#ccc;color:white;text-align:white-space:nowrap;center;vertical-align:middle;">
              {{ filename }}
            </nobr>

          {{/unless}}

          <input class="upload-ids" name="upload_ids[]" type="hidden" value="{{ id }}" />
        </td>

        <td style='width:100%;vertical-align:top;'>
          <ul class='unstyled'>
            {{#each variants}}

              <li>

                {{#if is_image}}

                  [<a href="{{ url }}" target="_blank"> view </a> | <a href="javascript:void(42)" data-toggle="collapse" data-target="#collapse-{{ id }}"> embed </a> | <a href="{{ url }}" class="upload-lightbox" title="{{ name }}/{{ filename }}">preview</a>]

                {{/if}}

                {{#unless is_image}}

                  [<a href="{{ url }}" target="_blank"> view </a> | <a href="javascript:void(42)" data-toggle="collapse" data-target="#collapse-{{ id }}"> embed </a>]

                {{/unless}}


                {{ name }}/{{ filename }}


                <div id="collapse-{{ id }}" class="collapse out">
                  <table class='unstyled'>

                  {{#if is_image}}
                    <tr>
                      <td style='text-align:right;'>markdown</td>
                      <td>&rarr;</td>
                      <td>
                        <a class='upload-embed markdown' href='javascript:void(42)'>
                          ![{{ filename }}]({{ url }})
                          <span class='upload-embed-content markdown' style='display:none'>![{{ filename }}]({{ url }})</span>
                        </a>
                      </td>
                    </tr>

                    <tr>
                      <td style='text-align:right;'>html</td>
                      <td>&rarr;</td>
                      <td>
                        <a class='upload-embed html' href='javascript:void(42)'>
                          &lt;img src="{{ url }}" /&gt
                          <span class='upload-embed-content html' style='display:none'><img src="{{ url }}"></span>
                        </a>
                      </td>
                    </tr>

                  {{/if}}

                    <tr>
                      <td style='text-align:right;'>url</td>
                      <td>&rarr;</td>
                      <td>
                        <a class='upload-embed raw' href='javascript:void(42)'>
                          {{ url }}
                          <span class='upload-embed-content raw' style='display:none'>{{ url }}</span>
                        </a>
                      </td>
                    </tr>

                  </table>
                </div>

              </li>

            {{/each}}
          </ul>
        <td>

        <td style='vertical-align:top;'>
          <span style='font-weight:bolder;font-size:1.2em;'>
            <a href='javascript:void(42)' title='remove {{ filename }}' class='upload-remove' data-id='{{ id }}'>&times;</a>
          </span>
        </td>
      </tr>

    </script>
  </table>


<!--
  the uploader widget
-->
  <table style='width:12em;'>
  <tr>
  <td>
  <div id="<%= domid %>" style=''>
    <noscript>
        <p>Please enable JavaScript to use file uploader.</p>
        <!-- or put a simple form for upload here -->
    </noscript>
  </div>
  </tr>
  </td>
  </table>


<!--
  teh js
-->

  <script>


    <% 
      
      session_key =
        Rails.application.config.session_options[:key] 

      upload_params = {
        session_key          => URI.escape(cookies[session_key]),

        'authenticity_token' => URI.escape(form_authenticity_token),

        'resize' => true
      }

      if config[:tmp] == false
        upload_params['tmp'] = false
      end

    %>


    jq(function(){
    //
      var template = Template('upload-row');
      var target = jq('#uploads');

    //
      <% 
        if false
           uploads = Upload.all.order_by(:created_at => :asc).limit(3)
        end
      %>

      var uploads = <%= j( defined?(uploads) ? Array(uploads).map(&:as_json) : [] ) %>;

      jQuery.each(uploads, function(){
        var upload = this;
        var html = template.render(upload);
        target.append(html);
      });

      var add_behavior_iff_needed = function(scope, selector, callback){
        var gaurd = selector + '-gaurd';

        scope.find(selector).each(function(){
          var element = jq(this);

          if(!element.data(gaurd)){
            callback(element);
            element.data(gaurd, true);
          };
        });
      };

      var add_behavior = function(){
        var scope = jq(arguments[0] || 'body');

        add_behavior_iff_needed(scope, '.upload-lightbox', function(e){
          e.colorbox({rel:'upload-lightbox', transition:"none", width:"80%", height:"80%"});
        });

        add_behavior_iff_needed(scope, '.upload-preview', function(e){
          e.click(function(){
            var selector = 'a.upload-lightbox[href="' + e.data('preview') + '"]';
            jq(selector).click();
          });
        });

        add_behavior_iff_needed(scope, '.upload-embed', function(e){
          e.click(function(){
            var content = e.find('.upload-embed-content').html();
            Upload.callbacks.embed(content);
          });
        });

        add_behavior_iff_needed(scope, '.upload-remove', function(e){
          e.click(function(){

            var id = e.data('id');
            var tr = e.closest('tr');
            var input = tr.find('input.upload-ids');

            var title = e.attr('title');

            if(e.data('removed')){
              input.removeAttr('disabled');
              input.removeAttr('readonly');

              //tr.css({'opacity' : '1.0'});
              tr.find('td').css({'opacity' : '1.0'});
              e.html('&times;');

              e.attr('title', title.replace(/\s*un-/, ''));

              Upload.callbacks.unremove(id);

              e.data('removed', false);
            } else {

              //if(confirm('Are you sure?')){
              if(true){
                input.attr('disabled', 'disabled');
                input.attr('readonly', 'readonly');

                //tr.css({'opacity' : '0.3'});
                tr.find('td').css({'opacity' : '0.3'});
                e.closest('td').css({'opacity' : '1.0'});
                e.html('&plus;');

                e.attr('title', 'un-' + title);

                Upload.callbacks.remove(id);

                e.data('removed', true);
              };

            }

          });
        });
      };

    //
      var options = {};

        options['element'] = document.getElementById(<%= j domid %>);

        options['params'] = <%= j upload_params %>;

        options['action'] = <%= j uploads_path %>;

        //options['debug'] = true;

        options['autoUpload'] = true;

        options['inputName'] = 'filename';

        options['uploadButtonText'] = 'Upload Files';

        options['dragText'] = 'Drop Files';

        //options['allowedExtensions'] = ['jpg', 'jpeg', 'png', 'gif'];

        options['showMessage'] = function(msg){ App.flash(msg, {'css.class':'alert-error'}) };

        options['onComplete'] = function(id, filename, response){
          var bool = Upload.callbacks.complete(response);
          if(!bool){ return; }

          var html = template.render(response);

          target.append(html);

          add_behavior();
        };

    //
      var uploader = new qq.FileUploader(options);

    //
      add_behavior();
    });


  </script>

app/views/shared/errors.html.erb
<div class="errors2html errors-summary">
  <h4 class="errors-caption">Sorry, we encountered some errors:</h4>

  <% unless errors.global.empty?  %>
    <ul class="errors-global-list">
      <% errors.global.each do |message| %>
        <li class="errors-message">
          <%= message %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <% unless errors.fields.empty?  %>
    <dl class="errors-fields-list">
      <% 
        errors.fields.each do |key, messages|
          title = Array(key).join(" ").titleize
      %>
        <dt class="errors-title">
          <%= title %>
        </dt>

        <% Array(messages).each do |message| %>
          <dd class="errors-message">
            <%= message %>
          </dd>
        <% end %>
      <% end %>
    </dl>
  <% end %>
</div>

app/views/shared/flash_messages.html.erb
<%
  list = messages!

  unless list.blank?
%>

  <div class='flash messages'>
  <% list.each do |msg, opts| %>
    <div class='<%= opts[:class] || :alert %> message'>
      <a class='dismiss close' href='javascript:void(42)'>&#215;</a>
      <%= msg.html_safe %>
    </div>
  <% end %>
  </div>

<% end %>

app/views/shared/get_device.html.erb
<%
  return_to = flash[:return_to] || '/'
%>

<script>
  jQuery(function(){
    var return_to = <%= j return_to %>;

    try { 
      var device = categorizr(); 
      alert(device);
      jQuery.cookie('device', (device || 'desktop'), {'path' : '/'});
    } catch(e) {};

    window.location = return_to;
  });
</script>