config/routes.rb
Dojo4::Application.routes.draw do
#
  extend Upload::Routes

#
  match "api(/*path(.:format))" => "api#index", :as => "api"

#
  scope(nil) do
    AuthController::Routes.each do |route|
      match "#{ route }(/:token)"   => "auth##{ route }", :as => "#{ route }"
    end
  end
  scope('auth') do
    AuthController::Routes.each do |route|
      match "#{ route }(/:token)"   => "auth##{ route }", :as => "auth_#{ route }"
    end
  end
  scope('admin') do
    AuthController::Routes.each do |route|
      match "#{ route }(/:token)"   => "admin/auth##{ route }", :as => "admin_#{ route }"
    end
  end
  scope('admin/auth') do
    AuthController::Routes.each do |route|
      match "#{ route }(/:token)"   => "admin/auth##{ route }", :as => "admin_auth_#{ route }"
    end
  end


#
  resources :invitations do
    member do
      match :accept
      match :decline
    end
  end


#
  match 'dashboard(/:action(/:id(.:format)))', :controller => 'dashboard', :as => 'dashboard'

## /su/jobs interface
#
=begin
  require 'resque'
  require 'resque/server'
  mount(Resque::Server => '/resque/jobs', :constraints => Constraints.admin)
=end


## admin
#
  namespace :admin do
    resources :users do
      match 'welcome', :action => 'welcome', :as => :welcome
    end

    location_routes = proc do
      resources :locations, :controller => 'locations'  do
        collection do
          match 'job/:id', :action => 'job'
          match 'import', :action => 'import'
        end
      end
    end
    instance_eval(&location_routes)

    resources :brands do
      instance_eval(&location_routes)
    end

    resources :reports do
      match 'attachments/:attachment_id', :action => 'attachment', :as => 'attachment', :via => 'get'
    end

    resources :uploads
  end

  match 'admin(/:action(/:id(.:format)))', :controller => 'admin/application', :as => 'admin'

## su
#
  namespace :su do
    resources :uploads
    resources :jobs
    match 'test(/:action(/:id(.:format)))', :controller => 'test'
  end
  match 'su(/:action(/:id(.:format)))', :controller => 'su/application', :as => 'su'


  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
    root :to => 'root#index', :as => :root

    match 'csrf' => 'application#csrf'
    match 'flash_messages' => 'application#flash_messages'

##
#
  scope ':brand' do
    match ':controller(/:action)(.:format)', :constraints => Constraints.brand
  end
  resources :brands do
    #match ':id/locator', :action => 'locator'
    member do
      match :locator
      match :contact
    end
  end

  resources :locations do
    collection do
      match :locator
    end
  end

  match 'javascript_jobs(/:action(/:id))(.:format)', :controller => 'javascript_jobs'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/report.rb
class Report
  include App::Document

  field(:title, :type => String)
  field(:kind, :type => String)
  field(:config, :type => Hash, :default => proc{ Hash.new })

  GridFS = ::Mongoid::GridFS

  has_and_belongs_to_many(:attachments, :class_name => '::Report::GridFS::File', :dependent => :destroy, :inverse_of => nil)

  validates_presence_of(:title)
  validates_presence_of(:kind)
  validates_inclusion_of(:kind, :in => proc{ Report.kinds })

  before_validation do |report|
    if report.created_at.blank?
      report.created_at = Time.now.utc
    end

    if report.updated_at.blank?
      report.updated_at = Time.now.utc
    end

    if report.title.blank?
      report.title = Report.title_for(report)
    end
  end

  def Report.title_for(*args)
    args.flatten!
    args.compact!

    reports, labels = args.partition{|arg| arg.is_a?(Report)}

    created_at = 
      if reports.size > 0
        reports.first.created_at || Time.now
      else
        nil
      end

    prefix = labels.map{|label| Slug.for(label)}.uniq

    prefix.delete('report')
    prefix.unshift('report') if prefix.blank?

    suffix = created_at.to_time.strftime('%Y%m%d%H%M%S') if created_at

    [prefix, suffix].compact.join('.')
  end

  def attach!(data, filename)
    io = data.respond_to?(:read) ? data : StringIO.new(data)
    grid_fs_file = GridFS.put(io, :filename => filename)
    attachments.push(grid_fs_file)
  end

  def Report.generator_for(*args, &block)
    Generator.for(*args, &block)
  end

  def Report.method_missing(method, *args, &block)
    super unless Generator.respond_to?(method)
    Generator.send(method, *args, &block)
  end

##
#
  class Generator < ::Dao::Conducer
  ##
  #
    def Generator.for(kind, params = {})
      kind = Generator.kind_for(kind)
      const = Generator.const_for(kind)

      if const_defined?(const)
        const_get(const).tap do |klass|
          instance = klass.new(kind, params || {})
          return instance
        end
      else
        raise NameError.new(kind.to_s)
      end
    end

    def Generator.generate(kind, params = {}, &block)
      Generator.for(kind, params).tap do |generator|
        generator.generate

        generator.report.attachments.each do |attachement|
          block.call(attachement) if block
        end
      end.report
    end

    def Generator.kinds
      @kinds ||= []
    end

    def Generator.kind_for(kind)
      (kind.is_a?(Class) ? kind.name : kind).to_s.split('::').last.underscore
    end

    def Generator.const_for(kind)
      kind = Generator.kind_for(kind)
      const = kind.camelize
    end

    def Generator.register(generator, &block)
      kind = Generator.kind_for(generator)
      kinds.push(kind)

      if block
        const = const_for(kind)
        remove_const(const) if const_defined?(const)
        klass = Class.new(Report::Generator)
        klass.class_eval(&block) if block
        const_set(const, klass)
      end

      kind
    ensure
      kinds.uniq!
    end

    def Generator.model_for(model_name)
      unless model_name.blank?
        model_name.to_s.constantize
      end
    end

    def Generator.timerange_for(starts_at, ends_at)
      unless starts_at.blank?
        inclusive_start_time = Coerce.time(starts_at).to_date.to_time(:utc)
      else
        inclusive_start_time = nil
      end

      unless ends_at.blank?
        exclusive_end_time = (Coerce.time(ends_at).to_date + 1).to_time(:utc)
      else
        exclusive_end_time = nil
      end

      [inclusive_start_time, exclusive_end_time]
    end

    def Generator.csv_for(fields, eachable)
      require 'csv' unless defined?(CSV)
      header = Coerce.list_of_strings(fields)

      CSV.generate do |csv|
        csv << header

        csv_rows_for(fields, eachable) do |row|
          csv << row
        end
      end
    end

    def Generator.csv_rows_for(fields, eachable, &block)
      rows = []
      fields = Coerce.list_of_strings(fields)

      eachable.each do |doc|
        row = fields.map{|field| (doc.respond_to?(field) ? doc.send(field) : doc.read_attribute(field)).to_s}
        block ? block.call(row) : rows.push(row)
      end
      
      block ? nil : rows
    end

    def Generator.json_for(rows)
      docs = rows.all.map(&:as_document)
      App.json_for(docs, :pretty => true)
    end

  ##
  #
    attr_accessor(:kind)
    attr_accessor(:report)

    def initialize(kind, params = {})
      @kind = Generator.kind_for(kind)
      @report = Report.new(:kind => @kind)

      if params.has_key?(form.name)
        update_attributes(
          params[form.name]
        )
      else
        update_attributes(
          params
        )
      end
    end
    
    def form_fields
      raise NotImplementedError
    end

    def generate
      raise NotImplementedError
    end
  end

##
#
  Dir.glob(Rails.root.join('lib/reports/generators/*.rb').to_s) do |file|
    ::Kernel.load(file)
  end
end

app/controllers/admin/reports_controller.rb
module Admin
  class ReportsController < Controller
    def new
    #
      @kind = params[:kind]
      @step = params[:step].to_i

    #
      if @step == 0
        if @kind.blank?
          if Report::Generator.kinds.size == 1
            @kind = Report::Generator.kinds.first
            redirect_to(url_for(:action => :new, :kind => @kind, :step => 1))
            return
          end
        end

        if request.get?
          render(:template => 'admin/reports/new')
          return
        else
          redirect_to(url_for(:action => :new, :kind => @kind, :step => 1))
          return
        end
      end

    #
      if @step == 1
        @generator = Report.generator_for(@kind, params)
        return if request.get?

        if @generator.generate
          message("#{ h @kind.inspect } report generated.", :class => :success)
          redirect_to(url_for(:action => :index))
          return
        else
          render(:template => 'admin/reports/new')
          return
        end
      end

    #
      render(:template => 'admin/reports/new')
    end

    def create
      new
    end

    def index
      @reports = Report.order_by(:created_at => :desc).page(params[:page]).per(10)
    end

    def show
      @reports = Report.order_by(:created_at => :desc).where(:id => params[:id]).page(params[:page]).per(10)
      @report = @reports.first

      if @report.attachments.size == 1
        @attachment = @report.attachments.first

        plaintext =
          case @attachment.content_type
            when %r{\Atext/.*}, 'application/json'
              true
            else
              false
          end

        if plaintext
          render(:template => 'admin/reports/attachment')
        else
          grid_fs_render(@attachment, :attachment => false)
        end

        return
      else
        render(:template => 'admin/reports/index')
      end
    end

    include Mongoid::GridFS::Helper

    def attachment
      @report = Report.find(params[:report_id] || params[:id])
      @attachment = @report.attachments.find(params[:attachment_id] || params[:id])

      if params[:download]
        grid_fs_render(@attachment, :attachment => true)
      else
        grid_fs_render(@attachment)
      end
    end
  end
end

app/views/admin/reports/attachment.html.erb
<%= render :template => 'admin/reports/index' %>
<pre style='font-size:0.75em;line-height:1.5em;'><%= @attachment.data -%></pre>

app/views/admin/reports/index.html.erb
<% unless current_action == 'show' %>

<%= link_to raw("New Report &rarr;"), url_for(:action => :new) %>
<br>
<br>

<% else %>

<%= link_to raw("&larr; All Reports"), url_for(:action => :index) %>
<br>
<br>

<% end %>

<table class='table table-striped'>
  <% @reports.each do |report| %>
  <tr>
    <th>
      Ttitle
    </th>
    <th>
      Created
    </th>
    <th>
      Config
    </th>
    <th>
      Downloads
    </th>
  </tr>

  <tr>

    <td>
      <%= link_to report.title, url_for(:action => :show, :id => report.id) %>
    </td>

    <td>
      <%= time_ago_in_words report.created_at %> ago
    </td>

    <td>
      <% if report.config.values.all?(&:blank?) %>
        ~
      <% else %>
        <ul>
        <% report.config.each do |key, val|; next if val.blank? %>
          <li>
            <%= key %>: <%= val %>
          </li>
        <% end %>
        </ul>
      <% end %>
    </td>

    <td>
      <ol>
      <% report.attachments.each do |attachment| %>
        <li>
          <%= link_to attachment.filename, admin_report_attachment_path(report.id, attachment.id), :target => :_report %>
          <small>
            <%= link_to '(download)', admin_report_attachment_path(report.id, attachment.id, :download => attachment.filename) %>
          </small>
        </li>
      <% end %>
      </ol>
    </td>

  </tr>
  <% end %>
</table>

<% unless current_action == 'show' %>

<br>
<%= paginate @reports %>

<% end %>

app/views/admin/reports/new.html.erb
<%= link_to raw("&larr; Reports"), url_for(:action => :index) %>
<br>
<br>

<% if @step == 0 %>

  <%= form(url_for(:action => :create), :class => 'app small', :id => 'kind_form') do |f| %>

    <h4 class='instructions'>
      Select a report kind:
    </h4>

    <dl>
      <dt>
        Kind
      </dt>
      <dd>
        <%= select_tag(:kind, options_for_select(Report.kinds)) %>
      </dd>
    </dl>

    <hr>
    <%= submit_tag(:Submit, :class => 'btn btn-success') %>
    <%= hidden_field_tag(:step, 0) %>
  <% end %>

<% end %>


<% if @step == 1 %>

  <%= form(url_for(:action => :create), :class => 'app small') do %>
    <%
      form = @generator.form
    %>

    <%= form.errors %>

    <h4 class='instructions'>
      Create a <%= @kind.inspect %> report:
    </h4>

    <%= @generator.form_fields %>

    <hr>
    <%= form.submit :class => 'btn btn-success' %>
    <%= hidden_field_tag(:step, 1) %>
    <%= hidden_field_tag(:kind, @kind) %>
  <% end %>

<% end %>

app/views/admin/reports/show.html.erb
<pre>
  <%=
    @report.inspect
  %>
</pre>